

export default function Page() {
  return (
    <div className="px-4 py-4">
      <h1 className="text-3xl font-bold">
        ed<span className="text-red-500 skew-x-12 scale-150 text-4xl">X</span>
      </h1>
      <p>
        edX is an open source e-learning platform, nowadays a lot of content was
        created and owned by edTech companies. So, edX is a platform where any
        teacher can share its content and any student can access to it for free.
        Also, users can interact with each other in discussion groups. Futher
        improve learning materials and can easily collaborate and work.
      </p>
      <div className="h-10"></div>
      <h1 className="text-3xl font-bold">
        Why ed
        <span className="text-red-500 skew-x-12 scale-150 text-4xl hover:skew-x-0">
          X
        </span>
        ?
      </h1>
      <p>
        Learning material for all, no publication, no copyright only free
        content either generated by AI, Free Education for all. This platform
        will cover every topic, every subject, every skill.
      </p>
    </div>
  );
}
